#!/bin/bash
rm -rf /k

pkg install termux-am -y &>/dev/null
termux-setup-storage & sleep 4 &>/dev/null

while true; do
  if [ -d /storage/shared ]; then
    break
  else
    echo "Storage permission denied"
  fi
  sleep 3
done

echo "Installing termux packages"
apt-get clean
apt-get update &>/dev/null 2>&1
apt-get -y --with-new-pkgs -o Dpkg::Options::="--force-confdef" upgrade &>/dev/null 2>&1
pkg install x11-repo -y &>/dev/null
pkg install pulseaudio -y &>/dev/null
pkg install wayland -y &>/dev/null
pkg install wget -y &>/dev/null
pkg install tsu -y &>/dev/null
pkg install root-repo -y &>/dev/null
pkg install patchelf -y &>/dev/null
pkg install p7zip -y &>/dev/null
pkg install xorg-xrandr -y &>/dev/null
pkg install ncurses-utils -y &>/dev/null
pkg install hashdeep -y &>/dev/null
pkg install termux-x11-nightly -y &>/dev/null

DEBIAN_FRONTEND=noninteractive apt update
DEBIAN_FRONTEND=noninteractive apt install -y xfce4 xfce4-terminal dbus-x11 x11-utils

if [ -e $PREFIX/glibc ]; then
  echo -n "Removing previous glibc. Continue? (Y/n) "
  read si
  if [ "$si" = "Y" ] || [ "$si" = "y" ]; then
    rm -rf $PREFIX/glibc
  else
    return 1
  fi
fi

INSTALL_WOW64=0

echo "Select an option"
echo "1) Install previous boxwine with box86"
echo "2) Install new boxwine wow64 version"
echo
echo -n "Selected number: "
read i
case "$i" in
  1)
    INSTALL_WOW64=0
    ;;
  2)
    INSTALL_WOW64=1
    ;;
  *)
    return 1
    ;;
esac

echo "Installing boxwine"

function wget-git-q {
  wget -q --retry-connrefused --tries=0 "https://gitlab.com/api/v4/projects/$PROJECT_ID/repository/files/$1/raw?ref=main"
  return $?
}

mkdir -p $PREFIX/glibc/opt/package-manager/installed

if [ "$INSTALL_WOW64" = "1" ]; then
  echo "PROJECT_ID=54244088" >$PREFIX/glibc/opt/package-manager/token
else
  echo "PROJECT_ID=54645223" >$PREFIX/glibc/opt/package-manager/token
fi

. $PREFIX/glibc/opt/package-manager/token
if ! wget-git-q "package-manager/package-manager" >"$PREFIX/glibc/opt/package-manager/package-manager"; then
  echo "Download failed"
  return 1
fi
chmod +x $PREFIX/glibc/opt/package-manager/package-manager
$PREFIX/glibc/opt/package-manager/package-manager sync-all

if [ "$INSTALL_WOW64" = "1" ]; then
  sync-package wine-9.3-vanilla-wow64
else
  sync-package wine-qq6-custom-8-25
fi

sync-package xfce4

cat >$PREFIX/bin/boxwine <<EOF
#!/bin/bash
export DISPLAY=:1
pulseaudio --start >/dev/null 2>&1
termux-x11 :1 &
sleep 2
xfce4-session &
EOF

chmod +x $PREFIX/bin/boxwine

echo "To start - type 'boxwine'"
